permissions:
  nether-portal: nether.portal
  end-portal: end.portal

messages:
  no-perms: "&cYou do not have permission to use this portal!"
  portal-charge: "&aYou've been charged &f$$portalcost &afor using this portal!"

global:
  pushback: true
  nether-portal-cost: 10.0
  end-portal-cost: 20.0
  # should the player be charged when coming back through the portal
  one-way-charge: true