name: PermissionPortals
version: '${project.version}'
main: me.ogali.permissionportals.PermissionPortals
api-version: 1.18
softdepend:
commands:
  pportalsadmin:
    aliases:
      - ppa
  permissionportals:
    aliases:
      - pportals
